version: '3.8'

services:
  web:
    image: ${CI_REGISTRY_IMAGE}/web:${IMAGE_VERSION}
    build:
      context: .
      target: web
      args:
        CI_REGISTRY_ARG: ${CI_REGISTRY}
        NODE_VERSION_ARG: ${NODE_VERSION}
    restart: unless-stopped
    networks:
      default:
      server_network:
        aliases:
          - ${COMPOSE_PROJECT_NAME}_web
    labels:
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/module=nginx"
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_web.rule=Host(`${HOST_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_web.entrypoints=webSecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_web.service=${COMPOSE_PROJECT_NAME}_web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_web.tls.certresolver=doDNSChallenge"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_web.middlewares=hstsHeader@file,secHeader@file${HTTP_ADDITIONAL_MIDDLEWARE}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_catcherWWW.rule=Host(`www.${HOST_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_catcherWWW.entrypoints=webSecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_catcherWWW.tls.certresolver=doDNSChallenge"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_catcherWWW.middlewares=${COMPOSE_PROJECT_NAME}_wwwRedirect"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_wwwRedirect.redirectregex.regex=^https://www.${HOST_DOMAIN}/(.*)"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_wwwRedirect.redirectregex.replacement=https://${HOST_DOMAIN}/$${1}"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_wwwRedirect.redirectregex.permanent=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_apiIPwhitelist.ipwhitelist.sourcerange=${HTTP_ALLOWED_IP}"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}_web.loadbalancer.server.scheme=http"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}_web.loadbalancer.server.port=80"
      - "traefik.docker.network=${SERVER_NETWORK_NAME}"
    env_file:
      - .env
    environment:
      APP_VERSION: ${IMAGE_VERSION}
    volumes:
      - web_log:/var/log/nginx:rw

volumes:
  web_log:

networks:
  default:
  server_network:
    external:
      name: ${SERVER_NETWORK_NAME}
