version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: web
      args: &APP_BUILD_ARGS
        NODE_VERSION_ARG: ${NODE_VERSION}
    restart: unless-stopped
    networks:
      default:
      server_network:
        aliases:
          - ${COMPOSE_PROJECT_NAME}_web
    depends_on:
      - app
    env_file: &APP_ENVS
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_web.rule=Host(`${HOST_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_web.entrypoints=webSecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_web.service=${COMPOSE_PROJECT_NAME}_web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_web.tls.certresolver=doDNSChallenge"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_web.middlewares=hstsHeader@file,secHeader@file"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_catcherWWW.rule=Host(`www.${HOST_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_catcherWWW.entrypoints=webSecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_catcherWWW.tls.certresolver=doDNSChallenge"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_catcherWWW.middlewares=${COMPOSE_PROJECT_NAME}_www-redirect"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_www-redirect.redirectregex.regex=^https://www.${HOST_DOMAIN}/(.*)"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_www-redirect.redirectregex.replacement=https://${HOST_DOMAIN}/$${1}"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_www-redirect.redirectregex.permanent=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}_web.loadbalancer.server.scheme=http"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}_web.loadbalancer.server.port=80"
      - "traefik.docker.network=${SERVER_NETWORK_NAME}"
    volumes:
      - web_log:/var/log/nginx:rw

volumes:
  web_log:

networks:
  default:
  server_network:
    external:
      name: ${SERVER_NETWORK_NAME}
